source 1.baseline/tables/1.AccessPoint.sql
source 1.baseline/tables/1.Destination.sql
source 1.baseline/tables/1.FolderType.sql
source 1.baseline/tables/1.FormatType.sql
source 1.baseline/tables/1.Language.sql
source 1.baseline/tables/1.MetadataSchema.sql
source 1.baseline/tables/1.ObjectFolderType.sql
source 1.baseline/tables/1.ObjectRelationType.sql
source 1.baseline/tables/1.ObjectType.sql
source 1.baseline/tables/1.Version.sql
source 1.baseline/tables/2.AccessPoint_Group_Join.sql
source 1.baseline/tables/2.AccessPoint_User_Join.sql
source 1.baseline/tables/2.AccessProvider.sql
source 1.baseline/tables/2.Folder.sql
source 1.baseline/tables/2.FormatCategory.sql
source 1.baseline/tables/2.MetadataSchema_Group_Join.sql
source 1.baseline/tables/2.MetadataSchema_User_Join.sql
source 1.baseline/tables/2.Object.sql
source 1.baseline/tables/3.AccessPoint_Object_Join.sql
source 1.baseline/tables/3.Folder_Group_Join.sql
source 1.baseline/tables/3.Folder_User_Join.sql
source 1.baseline/tables/3.Format.sql
source 1.baseline/tables/3.Metadata.sql
source 1.baseline/tables/3.Object_Folder_Join.sql
source 1.baseline/tables/3.Object_Object_Join.sql
source 1.baseline/tables/4.File.sql
source 1.baseline/tables/4.Object_Metadata_Join.sql
