source 3.storedprocedures/AccessPoint_Create.sql
source 3.storedprocedures/AccessPoint_Get.sql
source 3.storedprocedures/AccessPoint_Object_Join_Set.sql
source 3.storedprocedures/AccessPoint_User_Join_Set.sql
source 3.storedprocedures/AccessProvider_Create.sql
source 3.storedprocedures/DestinationInfo_Create.sql
source 3.storedprocedures/DestinationInfo_Get.sql
source 3.storedprocedures/File_Create.sql
source 3.storedprocedures/File_Delete.sql
source 3.storedprocedures/File_Get.sql
source 3.storedprocedures/FolderInfo_Get.sql
source 3.storedprocedures/FolderPermission_Get.sql
source 3.storedprocedures/FolderType_Create.sql
source 3.storedprocedures/FolderType_Delete.sql
source 3.storedprocedures/FolderType_Get.sql
source 3.storedprocedures/FolderType_Update.sql
source 3.storedprocedures/Folder_Create.sql
source 3.storedprocedures/Folder_Delete.sql
source 3.storedprocedures/Folder_Get.sql
source 3.storedprocedures/Folder_Get_DirectFolderAssociations.sql
source 3.storedprocedures/Folder_Group_Join_Set.sql
source 3.storedprocedures/Folder_Update.sql
source 3.storedprocedures/Folder_User_Join_Set.sql
source 3.storedprocedures/FormatCategory_Create.sql
source 3.storedprocedures/FormatCategory_Get.sql
source 3.storedprocedures/FormatType_Create.sql
source 3.storedprocedures/FormatType_Delete.sql
source 3.storedprocedures/FormatType_Get.sql
source 3.storedprocedures/FormatType_Update.sql
source 3.storedprocedures/Format_Create.sql
source 3.storedprocedures/Format_Get.sql
source 3.storedprocedures/Language_Create.sql
source 3.storedprocedures/Language_Delete.sql
source 3.storedprocedures/Language_Get.sql
source 3.storedprocedures/Language_Update.sql
source 3.storedprocedures/MetadataSchema_Create.sql
source 3.storedprocedures/MetadataSchema_Delete.sql
source 3.storedprocedures/MetadataSchema_Get.sql
source 3.storedprocedures/MetadataSchema_Update.sql
source 3.storedprocedures/Metadata_Get.sql
source 3.storedprocedures/Metadata_Set.sql
source 3.storedprocedures/ObjectFolderType_Create.sql
source 3.storedprocedures/ObjectRelationInfo_Get.sql
source 3.storedprocedures/ObjectRelationType_Create.sql
source 3.storedprocedures/ObjectRelationType_Delete.sql
source 3.storedprocedures/ObjectRelationType_Get.sql
source 3.storedprocedures/ObjectRelationType_Update.sql
source 3.storedprocedures/ObjectRelation_Delete.sql
source 3.storedprocedures/ObjectRelation_Set.sql
source 3.storedprocedures/ObjectRelation_SetMetadata.sql
source 3.storedprocedures/ObjectType_Delete.sql
source 3.storedprocedures/ObjectType_Get.sql
source 3.storedprocedures/ObjectType_Set.sql
source 3.storedprocedures/Object_Create.sql
source 3.storedprocedures/Object_Delete.sql
source 3.storedprocedures/Object_Folder_Join_Create.sql
source 3.storedprocedures/Object_Folder_Join_Delete.sql
source 3.storedprocedures/Object_Folder_Join_Update.sql
source 3.storedprocedures/Object_GetByFolderID.sql
source 3.storedprocedures/Object_GetByGUIDs.sql
source 3.storedprocedures/Object_GetByRelatedObjectGUID.sql
